DATASET_NAME = "cnn_dailymail"
DATASET_CONFIG = "3.0.0"
OUTPUT_DIR = "./qlora_results"
MODEL_SAVE_PATH = "./my_model"
JUDGE_MODEL = "Qwen/Qwen3-4B-Instruct-2507"
LORA_ADAPTERS_PATH = "./data"
INFERENCE_DEVICE = "cpu"

MODEL_NAME = "google/flan-t5-base"
MAX_INPUT_LENGTH = 512
MAX_TARGET_LENGTH = 128
MAX_NEW_TOKENS = 64
MAX_TOKENS_JUDGE = 124

LORA_R = 16
LORA_ALPHA = 32
LORA_DROPOUT = 0.05
TARGET_MODULES = ["q", "v", "wi", "wo"]

TRAIN_DEVICE = "cuda"
NUM_TRAIN_EPOCHS = 5
PER_DEVICE_TRAIN_BATCH_SIZE = 32
GRADIENT_ACCUMULATION_STEPS = 4
LEARNING_RATE = 3e-4
EVAL_STEPS = 30
SAVE_STEPS = 30
SAVE_TOTAL_LIMIT = 3
EARLY_STOPPING_PATIENCE = 3
DATALOADER_NUM_WORKERS = 8
TRAIN_SIZE = 4500
EVAL_SIZE=4500

BNB_4BIT_QUANT_TYPE = "nf4"
COMPUTE_DTYPE = "bfloat16"